sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t kjmorgan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kjmorgan/docker-react npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dkr-udmy"
  env: "Dkrudmy-env"
  bucket_name: "elasticbeanstalk-us-east-2-177712424507"
  bucket_path: "dkr-udmy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

